---
- name: noaa environment variables
  template:
    src: stb-Noaa.conf.j2
    dest: ~$USER/.stb-Noaa.conf
    owner: "{{ stb_owner }}"
    group: "{{ stb_group }}"
    mode: 0644

- name: predict directory
  file:
    path: ~$USER/.predict
    state: directory
    owner: "{{ stb_owner }}"
    group: "{{ stb_group }}"
    mode: 0755

- name: predict config file
  template:
    src: predict.qth.j2
    dest: ~$USER/.predict/predict.qth
    owner: "{{ stb_owner }}"
    group: "{{ stb_group }}"
    mode: 0644

- name: wxtoimg config file
  template:
    src: wxtoimgrc.j2
    dest: ~$USER/.wxtoimgrc
    owner: "{{ stb_owner }}"
    group: "{{ stb_group }}"
    mode: 0644

- name: wxtoimg license terms acceptance file
  copy:
    src: wxtoimglic
    dest: ~$USER/.wxtoimglic
    owner: "{{ stb_owner }}"
    group: "{{ stb_group }}"
    mode: 0644

- name: log directory for stb-Noaa logs
  become: yes
  file:
    path: /var/log/stb-Noaa
    state: directory
    owner: "{{ stb_owner }}"
    group: "{{ stb_group }}"
    mode: 0755

- name: logrotate settings for stb-Noaa logs
  become: yes
  copy:
    src: logrotate-settings
    dest: /etc/logrotate.d/stb-Noaa
    owner: root
    group: root
    mode: 0644

- name: gnuradio home directory
  file:
    path: ~$USER/.gnuradio
    state: directory
    owner: "{{ stb_owner }}"
    group: "{{ stb_group }}"
    mode: 0755

- name: gnuradio prefs directory
  file:
    path: ~$USER/.gnuradio/prefs
    state: directory
    owner: "{{ stb_owner }}"
    group: "{{ stb_group }}"
    mode: 0755

- name: gnuradio prefs file
  copy:
    src: vmcircbuf_default_factory
    dest: ~$USER/.gnuradio/prefs/vmcircbuf_default_factory
    owner: "{{ stb_owner }}"
    group: "{{ stb_group }}"
    mode: 0644

- name: disable wifi power mgmt script
  become: yes
  copy:
    src: disable-wifi-powermgmt.sh
    dest: /usr/local/sbin/disable-wifi-powermgmt.sh
    owner: root
    group: root
    mode: 0755
  when: disable_wifi_power_mgmt | bool
  register: wifi_powermgmt_script

- name: disable wifi power mgmt service definition
  become: yes
  copy:
    src: disable-wifi-powermgmt.service
    dest: /lib/systemd/system/disable-wifi-powermgmt.service
    owner: root
    group: root
    mode: 0644
  when: disable_wifi_power_mgmt | bool
  register: wifi_powermgmt_service

- name: enable systemd wifi power management disable service
  become: yes
  systemd:
    daemon_reload: yes
    name: disable-wifi-powermgmt.service
    enabled: yes
  when: (wifi_powermgmt_script.changed or wifi_powermgmt_service.changed) and (disable_wifi_power_mgmt|bool)

- name: annotation directory
  file:
    path: ~$USER/config/annotation
    state: directory
    owner: "{{ stb_owner }}"
    group: "{{ stb_group }}"
    mode: 0755

- name: annotation file (sample for modification)
  copy:
    src: annotation.html.j2_file
    dest: ~$USER/stb-Noaa/config/annotation/annotation.html.j2
    force: no
    owner: "{{ stb_owner }}"
    group: "{{ stb_group }}"
    mode: 0600

- name: annotation file image (sample for modification)
  copy:
    src: stb-noaa-logo.png
    dest: ~$USER/stb-Noaa/config/annotation/stb-noaa-logo.png
    force: no
    owner: "{{ stb_owner }}"
    group: "{{ stb_group }}"
    mode: 0600
...
