---
- name: install stb-Noaa core
  hosts: core
  connection: local
  gather_facts: no
  pre_tasks:
    - name: get os release
      shell: lsb_release -c --short
      register: ubuntu_version
      check_mode: no
      changed_when: no
  roles:
    - role: common
...
